export default [
  {
    originalQuote: "A może Bóg sobie mnie upatrzył na ateistę?",
    originalQuoteWordByWord: [
      "A",
      "może",
      "Bóg",
      "sobie",
      "mnie",
      "upatrzył",
      "na",
      "ateistę?",
    ],
    polishToRussianWordByWord: [
      "А",
      "может",
      "Бог",
      "себе",
      "меня",
      "выбрал",
      "на",
      "атеиста?",
    ],
    polishToRussianLiterary: "А может быть, Бог выбрал меня быть атеистом?",
    description:
      "Цитата играет на парадоксе: атеист, не верящий в существование Бога, оказывается как бы избран им. Это высмеивает религиозные догмы и предлагает задуматься о случайности или предопределенности веры.",
  },
  {
    originalQuote: "A może czyste ręce powinny być dłuższe?",
    originalQuoteWordByWord: [
      "A",
      "może",
      "czyste",
      "ręce",
      "powinny",
      "być",
      "dłuższe?",
    ],
    polishToRussianWordByWord: [
      "А",
      "может",
      "чистые",
      "руки",
      "должны",
      "быть",
      "длиннее?",
    ],
    polishToRussianLiterary: "А может быть, чистые руки должны быть длиннее?",
    description:
      "Здесь игра слов и метафора: 'чистые руки' — символ честности. Длинные руки могут символизировать необходимость влиять на большее количество вещей, чтобы оставаться честным.",
  },
  {
    originalQuote:
      "A może dopiero w świecie, który nie zna grawitacji, będzie opadanie na dno godne pogardy?",
    originalQuoteWordByWord: [
      "A",
      "może",
      "dopiero",
      "w",
      "świecie",
      "który",
      "nie",
      "zna",
      "grawitacji",
      "będzie",
      "opadanie",
      "na",
      "dno",
      "godne",
      "pogardy?",
    ],
    polishToRussianWordByWord: [
      "А",
      "может",
      "лишь",
      "в",
      "мире",
      "который",
      "не",
      "знает",
      "гравитации",
      "будет",
      "падение",
      "на",
      "дно",
      "достойное",
      "презрения?",
    ],
    polishToRussianLiterary:
      "А может быть, только в мире без гравитации падение на дно будет достойно презрения?",
    description:
      "Цитата наводит на мысль о том, что в мире без моральных ограничений (гравитации) любое падение становится бессмысленным. Это философский размышление о значении моральных норм.",
  },
  {
    originalQuote: "A może jesteśmy jedynie czyimś wspomnieniem?",
    originalQuoteWordByWord: [
      "A",
      "może",
      "jesteśmy",
      "jedynie",
      "czyimś",
      "wspomnieniem?",
    ],
    polishToRussianWordByWord: [
      "А",
      "может",
      "мы",
      "только",
      "чьим-то",
      "воспоминанием?",
    ],
    polishToRussianLiterary: "А может быть, мы всего лишь чье-то воспоминание?",
    description:
      "Цитата ставит под сомнение реальность нашего существования, предлагая идею, что мы можем быть всего лишь воспоминанием или иллюзией в чьем-то сознании.",
  },
  {
    originalQuote: "A może wykorzystamy kiedyś przemysłowo dusze ludzkie?",
    originalQuoteWordByWord: [
      "A",
      "może",
      "wykorzystamy",
      "kiedyś",
      "przemysłowo",
      "dusze",
      "ludzkie?",
    ],
    polishToRussianWordByWord: [
      "А",
      "может",
      "используем",
      "когда-то",
      "промышленно",
      "души",
      "человеческие?",
    ],
    polishToRussianLiterary:
      "А может быть, однажды мы начнем использовать человеческие души в промышленности?",
    description:
      "Саркастическое предположение о будущем, где даже души людей могут стать ресурсом в жестокой и бездушной индустриализации. Цитата критически освещает дегуманизацию и эксплуатацию в современном мире.",
  },
  {
    originalQuote:
      "A to będę się śmiał, gdy nie zdążą ze zniszczeniem świata przed jego końcem.",
    originalQuoteWordByWord: [
      "A",
      "to",
      "będę",
      "się",
      "śmiał",
      "gdy",
      "nie",
      "zdążą",
      "ze",
      "zniszczeniem",
      "świata",
      "przed",
      "jego",
      "końcem.",
    ],
    polishToRussianWordByWord: [
      "А",
      "это",
      "буду",
      "себя",
      "смеяться",
      "когда",
      "не",
      "успеют",
      "с",
      "разрушением",
      "мира",
      "перед",
      "его",
      "концом.",
    ],
    polishToRussianLiterary:
      "А я буду смеяться, когда они не успеют разрушить мир до его конца.",
    description:
      "Цитата высмеивает человеческие усилия по разрушению мира, предполагая, что мир может закончиться сам по себе до того, как мы его уничтожим. Это сатирический комментарий на тему самоуничтожения человечества.",
  },
  {
    originalQuote:
      "Aktor powinien mieć coś do powiedzenia, nawet jeśli ma niemą rolę.",
    originalQuoteWordByWord: [
      "Aktor",
      "powinien",
      "mieć",
      "coś",
      "do",
      "powiedzenia",
      "nawet",
      "jeśli",
      "ma",
      "niemą",
      "rolę.",
    ],
    polishToRussianWordByWord: [
      "Актёр",
      "должен",
      "иметь",
      "что-то",
      "для",
      "сказания",
      "даже",
      "если",
      "имеет",
      "немую",
      "роль.",
    ],
    polishToRussianLiterary:
      "Актёр должен иметь что сказать, даже если его роль немая.",
    description:
      "Цитата подчеркивает важность внутреннего содержания и мысли, даже когда внешние обстоятельства (в данном случае немая роль) не позволяют их выразить напрямую.",
  },
  {
    originalQuote: "Analfabeci muszą dyktować.",
    originalQuoteWordByWord: ["Analfabeci", "muszą", "dyktować."],
    polishToRussianWordByWord: ["Аналфабеты", "должны", "диктовать."],
    polishToRussianLiterary: "Неграмотные должны диктовать.",
    description:
      "Цитата выражает парадокс: люди, не обладающие знаниями и культурой, часто оказываются на позициях, где они диктуют условия остальным. Это критика социальных и политических реалий.",
  },
  {
    originalQuote:
      "Anonim jest tylko wtedy dopuszczalny, gdy piszący go rzeczywiście jest nikim.",
    originalQuoteWordByWord: [
      "Anonim",
      "jest",
      "tylko",
      "wtedy",
      "dopuszczalny",
      "gdy",
      "piszący",
      "go",
      "rzeczywiście",
      "jest",
      "nikim.",
    ],
    polishToRussianWordByWord: [
      "Аноним",
      "есть",
      "только",
      "тогда",
      "допустим",
      "когда",
      "пишущий",
      "его",
      "действительно",
      "есть",
      "никем.",
    ],
    polishToRussianLiterary:
      "Анонимность допустима только тогда, когда её автор действительно никто.",
    description:
      "Цитата иронично подчеркивает, что право на анонимность принадлежит лишь тем, кто не имеет значения или веса в обществе. Это размышление о ценности личности и мнения.",
  },
] as const;
