export default [
  {
    originalQuote: "Bada się głębię, rzucając w nią kamieniem.",
    originalQuoteWordByWord: [
      "Bada",
      "się",
      "głębię,",
      "rzucając",
      "w",
      "nią",
      "kamieniem.",
    ],
    polishToRussianWordByWord: [
      "Исследуют",
      "себя",
      "глубину,",
      "бросая",
      "в",
      "нее",
      "камнем.",
    ],
    polishToRussianLiterary: "Глубину исследуют, бросая в неё камень.",
    description:
      "Цитата использует метафору исследования неизведанного с помощью простых или грубых методов. Бросание камня символизирует грубое взаимодействие с чем-то глубоким и сложным.",
  },
  {
    originalQuote: "Bądź altruistą. Szanuj egoizm drugich.",
    originalQuoteWordByWord: [
      "Bądź",
      "altruistą.",
      "Szanuj",
      "egoizm",
      "drugich.",
    ],
    polishToRussianWordByWord: [
      "Будь",
      "альтруистом.",
      "Уважай",
      "эгоизм",
      "других.",
    ],
    polishToRussianLiterary: "Будь альтруистом. Уважай эгоизм других.",
    description:
      "Ироничная цитата, подчеркивающая парадокс человеческих отношений. Альтруизм предполагает самоотверженность, но здесь предлагается уважать эгоизм окружающих.",
  },
  {
    originalQuote: "Bądź realistą: nie mów prawdy.",
    originalQuoteWordByWord: ["Bądź", "realistą:", "nie", "mów", "prawdy."],
    polishToRussianWordByWord: [
      "Будь",
      "реалистом:",
      "не",
      "говори",
      "правды.",
    ],
    polishToRussianLiterary: "Будь реалистом: не говори правду.",
    description:
      "Цитата высмеивает жестокую правду о жизни, в которой правда часто не имеет значения или воспринимается негативно. Это циничный взгляд на общественные нормы.",
  },
  {
    originalQuote:
      "Bądźmy ludźmi, choćby tak długo, póki nauka nie odkryje, że jesteśmy czym innym.",
    originalQuoteWordByWord: [
      "Bądźmy",
      "ludźmi,",
      "choćby",
      "tak",
      "długo,",
      "póki",
      "nauka",
      "nie",
      "odkryje,",
      "że",
      "jesteśmy",
      "czym",
      "innym.",
    ],
    polishToRussianWordByWord: [
      "Будем",
      "людьми,",
      "хотя",
      "так",
      "долго,",
      "пока",
      "наука",
      "не",
      "откроет,",
      "что",
      "мы",
      "чем-то",
      "иным.",
    ],
    polishToRussianLiterary:
      "Давайте будем людьми, хотя бы до тех пор, пока наука не докажет, что мы нечто другое.",
    description:
      "Ироничное высказывание о человеческой сущности. Лец предлагает, что наука может изменить наше восприятие самих себя, но пока этого не случилось, стоит оставаться людьми.",
  },
  {
    originalQuote: "Błoto stwarza czasem pozory głębi.",
    originalQuoteWordByWord: ["Błoto", "stwarza", "czasem", "pozory", "głębi."],
    polishToRussianWordByWord: [
      "Грязь",
      "создает",
      "иногда",
      "видимость",
      "глубины.",
    ],
    polishToRussianLiterary: "Грязь иногда создает иллюзию глубины.",
    description:
      "Метафорическое высказывание о том, что поверхностное или незначительное может казаться глубоким и значимым. Это критика поверхностных людей или идей, которые создают впечатление важности.",
  },
  {
    originalQuote: "Bogowie dziedziczą po sobie przymioty i wiernych.",
    originalQuoteWordByWord: [
      "Bogowie",
      "dziedziczą",
      "po",
      "sobie",
      "przymioty",
      "i",
      "wiernych.",
    ],
    polishToRussianWordByWord: [
      "Боги",
      "наследуют",
      "после",
      "себя",
      "свойства",
      "и",
      "верующих.",
    ],
    polishToRussianLiterary: "Боги наследуют друг у друга черты и верующих.",
    description:
      "Цитата о том, как религиозные системы и верования передаются и развиваются от одной эпохи к другой, сохраняющие как свои качества, так и последователей.",
  },
  {
    originalQuote: "Bogu, co boskie, cesarzowi, co cesarskie. A co ludziom?",
    originalQuoteWordByWord: [
      "Bogu,",
      "co",
      "boskie,",
      "cesarzowi,",
      "co",
      "cesarskie.",
      "A",
      "co",
      "ludziom?",
    ],
    polishToRussianWordByWord: [
      "Богу,",
      "что",
      "божественное,",
      "императору,",
      "что",
      "императорское.",
      "А",
      "что",
      "людям?",
    ],
    polishToRussianLiterary:
      "Богу — божественное, императору — императорское. А что людям?",
    description:
      "Философское размышление о справедливости и распределении. Лец задается вопросом, что остается для обычных людей, если боги и власть имущие уже получили своё.",
  },
  {
    originalQuote: "Bosy nie stąpa po różach.",
    originalQuoteWordByWord: ["Bosy", "nie", "stąpa", "po", "różach."],
    polishToRussianWordByWord: ["Босой", "не", "ступает", "по", "розам."],
    polishToRussianLiterary: "Босой не ходит по розам.",
    description:
      "Цитата подразумевает, что человек без защиты (или поддержки) не может наслаждаться красотой или комфортом, так как ему приходится сталкиваться с трудностями напрямую.",
  },
  {
    originalQuote: "Był pijany ojczyzną, włączając w to jej alkohol.",
    originalQuoteWordByWord: [
      "Był",
      "pijany",
      "ojczyzną,",
      "włączając",
      "w",
      "to",
      "jej",
      "alkohol.",
    ],
    polishToRussianWordByWord: [
      "Был",
      "пьян",
      "родиной,",
      "включая",
      "в",
      "это",
      "ее",
      "алкоголь.",
    ],
    polishToRussianLiterary: "Он был пьян своей родиной, включая её алкоголь.",
    description:
      "Метафорическое выражение, которое подчеркивает любовь к родине, смешанную с пороками, такими как алкоголь. Это может быть критикой патриотизма, скрывающего социальные проблемы.",
  },
  {
    originalQuote:
      "Byłem raz w domu sprawiedliwości, jej dzieci bawiły się w ciuciubabkę.",
    originalQuoteWordByWord: [
      "Byłem",
      "raz",
      "w",
      "domu",
      "sprawiedliwości,",
      "jej",
      "dzieci",
      "bawiły",
      "się",
      "w",
      "ciuciubabkę.",
    ],
    polishToRussianWordByWord: [
      "Я",
      "однажды",
      "в",
      "доме",
      "справедливости,",
      "её",
      "дети",
      "играли",
      "себя",
      "в",
      "прятки.",
    ],
    polishToRussianLiterary:
      "Я однажды был в доме справедливости, её дети играли в прятки.",
    description:
      "Ироничное выражение о том, что даже в местах, где должна царить справедливость, можно встретить абсурд и хаос. 'Прятки' символизируют сокрытие истины или бесполезные попытки её найти.",
  },
  {
    originalQuote:
      "Były dwie możliwości: albo stanąć na gruncie ich zasad, albo zawisnąć nad nimi.",
    originalQuoteWordByWord: [
      "Były",
      "dwie",
      "możliwości:",
      "albo",
      "stanąć",
      "na",
      "gruncie",
      "ich",
      "zasad,",
      "albo",
      "zawisnąć",
      "nad",
      "nimi.",
    ],
    polishToRussianWordByWord: [
      "Было",
      "две",
      "возможности:",
      "либо",
      "встать",
      "на",
      "почве",
      "их",
      "принципов,",
      "либо",
      "повиснуть",
      "над",
      "ними.",
    ],
    polishToRussianLiterary:
      "Было два варианта: либо следовать их принципам, либо повиснуть над ними.",
    description:
      "Цитата выражает выбор между принятием чужих правил или сопротивлением, что может привести к опасности. Здесь отражается конфликт между системой и личной свободой.",
  },
] as const;
