export default [
  {
    originalQuote:
      "Celność słów? Ba! Każdy dobry komendant plutonu egzekucyjnego ją posiada.",
    originalQuoteWordByWord: [
      "Celność",
      "słów?",
      "Ba!",
      "Każdy",
      "dobry",
      "komendant",
      "plutonu",
      "egzekucyjnego",
      "ją",
      "posiada.",
    ],
    polishToRussianWordByWord: [
      "Точность",
      "слов?",
      "Ба!",
      "Каждый",
      "хороший",
      "командир",
      "расстрельного",
      "взвода",
      "ее",
      "обладает.",
    ],
    polishToRussianLiterary:
      "Точность слов? Ба! Каждый хороший командир расстрельного взвода ею обладает.",
    description:
      "Ирония в том, что 'точность слов' ассоциируется с умением точно выражать мысли, а здесь она приписана командиру расстрельного взвода — тому, кто приказывает стрелять, а не обсуждать.",
  },
  {
    originalQuote: "Cezarów zabijają zazwyczaj przyjaciele. Bo są wrogami.",
    originalQuoteWordByWord: [
      "Cezarów",
      "zabijają",
      "zazwyczaj",
      "przyjaciele.",
      "Bo",
      "są",
      "wrogami.",
    ],
    polishToRussianWordByWord: [
      "Цезарей",
      "убивают",
      "как правило",
      "друзья.",
      "Потому что",
      "они",
      "враги.",
    ],
    polishToRussianLiterary:
      "Цезарей обычно убивают друзья. Потому что они враги.",
    description:
      "Цитата отсылает к известной истории убийства Цезаря его ближайшими друзьями. Смысл заключается в том, что иногда самые близкие люди становятся самыми опасными врагами.",
  },
  {
    originalQuote:
      "Cienie? Rzecz najbardziej optymistyczna. Dowód na istnienie wokoło światła.",
    originalQuoteWordByWord: [
      "Cienie?",
      "Rzecz",
      "najbardziej",
      "optymistyczna.",
      "Dowód",
      "na",
      "istnienie",
      "wokoło",
      "światła.",
    ],
    polishToRussianWordByWord: [
      "Тени?",
      "Вещь",
      "наиболее",
      "оптимистичная.",
      "Доказательство",
      "на",
      "существование",
      "вокруг",
      "света.",
    ],
    polishToRussianLiterary:
      "Тени? Самая оптимистичная вещь. Доказательство существования света вокруг.",
    description:
      "Обычно тени ассоциируются с чем-то негативным, но Лец интерпретирует их как доказательство присутствия света. Здесь прослеживается философский оптимизм, несмотря на темные стороны жизни.",
  },
  {
    originalQuote: "Ceń słowa. Każde może być twoim ostatnim.",
    originalQuoteWordByWord: [
      "Ceń",
      "słowa.",
      "Każde",
      "może",
      "być",
      "twoim",
      "ostatnim.",
    ],
    polishToRussianWordByWord: [
      "Цени",
      "слова.",
      "Каждое",
      "может",
      "быть",
      "твоим",
      "последним.",
    ],
    polishToRussianLiterary: "Цени слова. Каждое может быть твоим последним.",
    description:
      "Лец напоминает о важности слов, ведь каждое из них может оказаться последним. Это философский взгляд на силу и значимость слов.",
  },
  {
    originalQuote: "Chcesz ukryć twarz – wyjdź nago.",
    originalQuoteWordByWord: [
      "Chcesz",
      "ukryć",
      "twarz",
      "–",
      "wyjdź",
      "nago.",
    ],
    polishToRussianWordByWord: [
      "Хочешь",
      "скрыть",
      "лицо",
      "–",
      "выйди",
      "нагим.",
    ],
    polishToRussianLiterary: "Хочешь скрыть лицо – выйди нагим.",
    description:
      "Цитата говорит о парадоксе: когда ты совершенно открыт (выйдешь нагим), лицо, символ твоей личности, становится менее заметным. Это ироничный взгляд на человеческую природу и социальные маски.",
  },
  {
    originalQuote:
      "Chciałem powiedzieć światu tylko jedno słowo. Ponieważ nie potrafiłem tego, stałem się pisarzem.",
    originalQuoteWordByWord: [
      "Chciałem",
      "powiedzieć",
      "światu",
      "tylko",
      "jedno",
      "słowo.",
      "Ponieważ",
      "nie",
      "potrafiłem",
      "tego,",
      "stałem",
      "się",
      "pisarzem.",
    ],
    polishToRussianWordByWord: [
      "Хотел",
      "сказать",
      "миру",
      "только",
      "одно",
      "слово.",
      "Потому",
      "что",
      "не",
      "смог",
      "этого,",
      "стал",
      "писателем.",
    ],
    polishToRussianLiterary:
      "Я хотел сказать миру всего одно слово. Поскольку не смог этого сделать, я стал писателем.",
    description:
      "Лец подчеркивает сложность выразить глубокую мысль одним словом, иронично замечая, что писательство стало его альтернативой неудаче в этом деле.",
  },
  {
    originalQuote: "Chcesz zagłuszyć głos swego serca? Zdobądź poklask tłumu.",
    originalQuoteWordByWord: [
      "Chcesz",
      "zagłuszyć",
      "głos",
      "swego",
      "serca?",
      "Zdobądź",
      "poklask",
      "tłumu.",
    ],
    polishToRussianWordByWord: [
      "Хочешь",
      "заглушить",
      "голос",
      "своего",
      "сердца?",
      "Завоюй",
      "аплодисменты",
      "толпы.",
    ],
    polishToRussianLiterary:
      "Хочешь заглушить голос своего сердца? Завоюй аплодисменты толпы.",
    description:
      "Здесь Лец иронизирует над тем, как легко утратить свою индивидуальность, получив общественное признание и одобрение, что может привести к потере собственного 'я'.",
  },
  {
    originalQuote: "Chleb otwiera każde usta.",
    originalQuoteWordByWord: ["Chleb", "otwiera", "każde", "usta."],
    polishToRussianWordByWord: ["Хлеб", "открывает", "каждый", "рот."],
    polishToRussianLiterary: "Хлеб открывает любые уста.",
    description:
      "Эта цитата подчеркивает важность материального обеспечения. Даже самые стойкие принципы могут пасть перед простыми нуждами.",
  },
  {
    originalQuote: "Chodź własnymi drogami nawet po obcych rajach.",
    originalQuoteWordByWord: [
      "Chodź",
      "własnymi",
      "drogami",
      "nawet",
      "po",
      "obcych",
      "rajach.",
    ],
    polishToRussianWordByWord: [
      "Иди",
      "своими",
      "путями",
      "даже",
      "по",
      "чужим",
      "раям.",
    ],
    polishToRussianLiterary: "Иди своими путями, даже если ты в чужом раю.",
    description:
      "Здесь Лец говорит о важности следовать своим принципам и путям, даже если окружение предлагает иллюзию благополучия (чужой рай).",
  },
  {
    originalQuote: "Chociaż krowie dasz kakao, nie wydoisz czekolady.",
    originalQuoteWordByWord: [
      "Chociaż",
      "krowie",
      "dasz",
      "kakao,",
      "nie",
      "wydoisz",
      "czekolady.",
    ],
    polishToRussianWordByWord: [
      "Хотя",
      "корове",
      "дашь",
      "какао,",
      "не",
      "сдоишь",
      "шоколад.",
    ],
    polishToRussianLiterary: "Хотя ты и дашь корове какао, шоколад не сдоишь.",
    description:
      "Ироничная метафора о том, что не все усилия приведут к ожидаемому результату, даже если вложить все необходимое. Лец шутит о наивных ожиданиях.",
  },
  {
    originalQuote:
      "Ci, co mają szersze horyzonty, mają zazwyczaj gorsze perspektywy.",
    originalQuoteWordByWord: [
      "Ci,",
      "co",
      "mają",
      "szersze",
      "horyzonty,",
      "mają",
      "zazwyczaj",
      "gorsze",
      "perspektywy.",
    ],
    polishToRussianWordByWord: [
      "Те,",
      "кто",
      "имеют",
      "более широкие",
      "горизонты,",
      "имеют",
      "как правило",
      "хуже",
      "перспективы.",
    ],
    polishToRussianLiterary:
      "Те, у кого более широкие горизонты, как правило, имеют худшие перспективы.",
    description:
      "Цитата иронично подчеркивает, что люди с широким кругозором и большими идеями часто сталкиваются с трудностями в реальной жизни. Их видение шире, но это может привести к разочарованию или нехватке возможностей.",
  },
  {
    originalQuote: "Ci, co przerośli epokę, chodzą ze spuszczoną głową.",
    originalQuoteWordByWord: [
      "Ci,",
      "co",
      "przerośli",
      "epokę,",
      "chodzą",
      "ze",
      "spuszczoną",
      "głową.",
    ],
    polishToRussianWordByWord: [
      "Те,",
      "кто",
      "переросли",
      "эпоху,",
      "ходят",
      "с",
      "опущенной",
      "головой.",
    ],
    polishToRussianLiterary:
      "Те, кто переросли свою эпоху, ходят с опущенной головой.",
    description:
      "Люди, опередившие свое время, могут чувствовать себя чужими в обществе, что заставляет их чувствовать разочарование и грусть.",
  },
  {
    originalQuote: "Ci, co śnią, mają noce bezsenne.",
    originalQuoteWordByWord: [
      "Ci,",
      "co",
      "śnią,",
      "mają",
      "noce",
      "bezsenne.",
    ],
    polishToRussianWordByWord: [
      "Те,",
      "кто",
      "снят,",
      "имеют",
      "бессонные",
      "ночи.",
    ],
    polishToRussianLiterary: "Те, кто мечтает, имеют бессонные ночи.",
    description:
      "Лец подчеркивает напряжение между мечтами и реальностью. Большие мечты часто приносят тревогу и бессонные ночи, когда нужно воплотить их в жизнь.",
  },
  {
    originalQuote:
      "Ci, którzy mają ideę wciąż w gębie, mają ją zazwyczaj i w pobliskim nosie.",
    originalQuoteWordByWord: [
      "Ci,",
      "którzy",
      "mają",
      "ideę",
      "wciąż",
      "w",
      "gębie,",
      "mają",
      "ją",
      "zazwyczaj",
      "i",
      "w",
      "pobliskim",
      "nosie.",
    ],
    polishToRussianWordByWord: [
      "Те,",
      "кто",
      "имеют",
      "идею",
      "вечно",
      "в",
      "рту,",
      "имеют",
      "ее",
      "обычно",
      "и",
      "в",
      "ближайшем",
      "носу.",
    ],
    polishToRussianLiterary:
      "Те, кто вечно говорят об идее, обычно имеют её и в ближайшем носу.",
    description:
      "Цитата высмеивает людей, которые много говорят об идеях, но в действительности их не реализуют. Ироничный сарказм о пустословии.",
  },
] as const;
