export default [
  {
    originalQuote: "Ciasnota umysłowa się rozszerza!",
    originalQuoteWordByWord: ["Ciasnota", "umysłowa", "się", "rozszerza"],
    polishToRussianWordByWord: ["Теснота", "умственная", "себя", "расширяет"],
    polishToRussianLiterary: "Умственная узость расширяется!",
    description:
      "Ирония в том, что узость мышления, которая по своей сути ограничивает, здесь противопоставляется расширению. Это парадокс, подчеркивающий, как ограниченность может охватывать всё больше областей жизни.",
  },
  {
    originalQuote: "Ciemne okna są czasem bardzo jasnym dowodem.",
    originalQuoteWordByWord: [
      "Ciemne",
      "okna",
      "są",
      "czasem",
      "bardzo",
      "jasnym",
      "dowodem",
    ],
    polishToRussianWordByWord: [
      "Тёмные",
      "окна",
      "являются",
      "иногда",
      "очень",
      "ясным",
      "доказательством",
    ],
    polishToRussianLiterary:
      "Тёмные окна иногда являются очень ясным доказательством.",
    description:
      "Фраза играет на противопоставлении «тёмного» и «ясного», указывая на то, что отсутствие информации или закрытость иногда могут быть самыми сильными доказательствами чего-либо.",
  },
  {
    originalQuote: "Ciemno w tym państwie, gdzie łotry na świeczniku.",
    originalQuoteWordByWord: [
      "Ciemno",
      "w",
      "tym",
      "państwie",
      "gdzie",
      "łotry",
      "na",
      "świeczniku",
    ],
    polishToRussianWordByWord: [
      "Тёмно",
      "в",
      "этой",
      "стране",
      "где",
      "негодяи",
      "на",
      "светильнике",
    ],
    polishToRussianLiterary: "Темно в той стране, где подлецы на пьедестале.",
    description:
      "Лец использует метафору «свечи» и «пьедестала», чтобы показать, как в обществе наступает мрак, когда власть и почести оказываются у недостойных людей.",
  },
  {
    originalQuote: "Ciułamy nasze myśli – może uzbieramy jakiś sens.",
    originalQuoteWordByWord: [
      "Ciułamy",
      "nasze",
      "myśli",
      "może",
      "uzbieramy",
      "jakiś",
      "sens",
    ],
    polishToRussianWordByWord: [
      "Копим",
      "наши",
      "мысли",
      "может",
      "соберём",
      "какой-то",
      "смысл",
    ],
    polishToRussianLiterary:
      "Мы копим мысли — может, соберём хоть какой-то смысл.",
    description:
      "Автор иронизирует над тем, как люди собирают свои мысли, надеясь, что со временем они приобретут смысл. Однако фраза выражает сомнение в том, что из хаоса мыслей действительно получится что-то значимое.",
  },
  {
    originalQuote: "Co kuleje – idzie.",
    originalQuoteWordByWord: ["Co", "kuleje", "idzie"],
    polishToRussianWordByWord: ["Что", "хромает", "идёт"],
    polishToRussianLiterary: "Что хромает — всё равно идёт.",
    description:
      "Это выражение подразумевает, что даже что-то повреждённое или недостаточное всё равно продолжает существовать или двигаться вперёд, несмотря на свои недостатки.",
  },
  {
    originalQuote: "Co może powstać z niczego? Prowokacja.",
    originalQuoteWordByWord: [
      "Co",
      "może",
      "powstać",
      "z",
      "niczego",
      "Prowokacja",
    ],
    polishToRussianWordByWord: [
      "Что",
      "может",
      "возникнуть",
      "из",
      "ничего",
      "Провокация",
    ],
    polishToRussianLiterary: "Что может возникнуть из ничего? Провокация.",
    description:
      "Провокация, по Лецу, часто рождается из пустоты, намекая на то, что иногда из совершенно незначительных вещей можно создать конфликт или проблему.",
  },
  {
    originalQuote: "Co niszczy siłę przyciągania? Przyzwyczajenie.",
    originalQuoteWordByWord: [
      "Co",
      "niszczy",
      "siłę",
      "przyciągania",
      "Przyzwyczajenie",
    ],
    polishToRussianWordByWord: [
      "Что",
      "разрушает",
      "силу",
      "притяжения",
      "Привычка",
    ],
    polishToRussianLiterary: "Что разрушает силу притяжения? Привычка.",
    description:
      "Автор показывает, что со временем даже сильное притяжение может угаснуть под воздействием привычки, намекая на рутину в отношениях и жизни.",
  },
  {
    originalQuote: "Co spadło nam z nieba? Szatan.",
    originalQuoteWordByWord: ["Co", "spadło", "nam", "z", "nieba", "Szatan"],
    polishToRussianWordByWord: ["Что", "упало", "нам", "с", "неба", "Сатана"],
    polishToRussianLiterary: "Что упало нам с неба? Сатана.",
    description:
      "Это саркастическая фраза, где Лец противопоставляет ожидаемое чудо или божественное вмешательство с тем, что на самом деле с неба приходит зло или беда.",
  },
  {
    originalQuote:
      "Co to jest Chaos? To jest Ład, który zniszczono przy Stworzeniu Świata.",
    originalQuoteWordByWord: [
      "Co",
      "to",
      "jest",
      "Chaos",
      "To",
      "jest",
      "Ład",
      "który",
      "zniszczono",
      "przy",
      "Stworzeniu",
      "Świata",
    ],
    polishToRussianWordByWord: [
      "Что",
      "это",
      "есть",
      "Хаос",
      "Это",
      "есть",
      "Порядок",
      "который",
      "разрушен",
      "при",
      "Создании",
      "Мира",
    ],
    polishToRussianLiterary:
      "Что такое хаос? Это порядок, разрушенный при создании мира.",
    description:
      "Лец видит в хаосе нечто изначально гармоничное, но разрушенное процессом творения, что является философским размышлением о природе вселенной.",
  },
  {
    originalQuote: "Co trzyma nas na tym globie prócz siły ciążenia?",
    originalQuoteWordByWord: [
      "Co",
      "trzyma",
      "nas",
      "na",
      "tym",
      "globie",
      "prócz",
      "siły",
      "ciążenia",
    ],
    polishToRussianWordByWord: [
      "Что",
      "держит",
      "нас",
      "на",
      "этом",
      "шаре",
      "кроме",
      "силы",
      "тяжести",
    ],
    polishToRussianLiterary: "Что держит нас на этом шаре, кроме силы тяжести?",
    description:
      "Фраза заставляет задуматься о нематериальных вещах, таких как эмоции, отношения или смысл жизни, которые могут быть важнее, чем простая физика.",
  },
  {
    originalQuote:
      "Cóż, jedni mówią o tym, że jest na poziomie, inni, że dno? Obie strony mają rację, przy tej płyciźnie wszystko jedno.",
    originalQuoteWordByWord: [
      "Cóż",
      "jedni",
      "mówią",
      "o",
      "tym",
      "że",
      "jest",
      "na",
      "poziomie",
      "inni",
      "że",
      "dno",
      "Obie",
      "strony",
      "mają",
      "rację",
      "przy",
      "tej",
      "płyciźnie",
      "wszystko",
      "jedno",
    ],
    polishToRussianWordByWord: [
      "Ну",
      "одни",
      "говорят",
      "о",
      "этом",
      "что",
      "есть",
      "на",
      "уровне",
      "другие",
      "что",
      "дно",
      "Обе",
      "стороны",
      "имеют",
      "право",
      "при",
      "этой",
      "мелководье",
      "всё",
      "одно",
    ],
    polishToRussianLiterary:
      "Ну что ж, одни говорят, что это на уровне, другие — что это дно. Оба правы, при такой мелкости всё равно.",
    description:
      "Циничное наблюдение о том, как неглубокие вещи или люди могут быть оценены диаметрально противоположными мнениями, но оба мнения будут правы из-за поверхностности объекта.",
  },
  {
    originalQuote: "Cóż, pięknie dźwięczy nawet nocnik z prawdziwej porcelany.",
    originalQuoteWordByWord: [
      "Cóż",
      "pięknie",
      "dźwięczy",
      "nawet",
      "nocnik",
      "z",
      "prawdziwej",
      "porcelany",
    ],
    polishToRussianWordByWord: [
      "Ну",
      "красиво",
      "звенит",
      "даже",
      "горшок",
      "из",
      "настоящего",
      "фарфора",
    ],
    polishToRussianLiterary:
      "Ну что ж, даже ночной горшок из настоящего фарфора красиво звенит.",
    description:
      "Фраза иронично подчёркивает, что внешний вид или материал не изменяют суть объекта, а ночной горшок остаётся ночным горшком, несмотря на свою утончённую форму.",
  },
  {
    originalQuote:
      "Cóż wiem o kobiecie? No cóż, że dopiero z mężczyzną tworzą człowieka.",
    originalQuoteWordByWord: [
      "Cóż",
      "wiem",
      "o",
      "kobiecie",
      "No",
      "cóż",
      "że",
      "dopiero",
      "z",
      "mężczyzną",
      "tworzą",
      "człowieka",
    ],
    polishToRussianWordByWord: [
      "Что",
      "знаю",
      "о",
      "женщине",
      "Ну",
      "что",
      "что",
      "только",
      "с",
      "мужчиной",
      "создают",
      "человека",
    ],
    polishToRussianLiterary:
      "Что я знаю о женщине? Ну, что только с мужчиной они создают человека.",
    description:
      "Лец размышляет о женщине и мужчине как о половинах одного целого, намекая на необходимость союза двух полов для создания полноценного человека.",
  },
  {
    originalQuote:
      "Cóż za samodzielność! Kultura może się obejść bez ministra, ale minister również bez kultury.",
    originalQuoteWordByWord: [
      "Cóż",
      "za",
      "samodzielność!",
      "Kultura",
      "może",
      "się",
      "obejść",
      "bez",
      "ministra",
      "ale",
      "minister",
      "również",
      "bez",
      "kultury",
    ],
    polishToRussianWordByWord: [
      "Какая",
      "за",
      "самостоятельность!",
      "Культура",
      "может",
      "себя",
      "обойтись",
      "без",
      "министра",
      "но",
      "министр",
      "также",
      "без",
      "культуры",
    ],
    polishToRussianLiterary:
      "Какая независимость! Культура может обойтись без министра, но и министр может без культуры.",
    description:
      "Здесь Лец иронизирует над тем, как культура и власть существуют независимо друг от друга, подчёркивая возможную отчуждённость чиновников от культурных ценностей.",
  },
] as const;
